// Action types
export const LOAD_PRODUCTS_START = 'LOAD_PRODUCTS_START';
export const LOAD_PRODUCTS_END = 'LOAD_PRODUCTS_END';
export const LOAD_PRODUCTS_ERROR = 'LOAD_PRODUCTS_ERROR';

export const LOAD_CART_START = 'LOAD_CART_START';
export const LOAD_CART_END = 'LOAD_CART_END';
export const LOAD_CART_ERROR = 'LOAD_CART_ERROR';

export const ADD_TO_CART_START = 'ADD_TO_CART_START';
export const ADD_TO_CART_END = 'ADD_TO_CART_END';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';

export const UPDATE_CART_START = 'UPDATE_CART_START';
export const UPDATE_CART_END = 'UPDATE_CART_END';
export const UPDATE_CART_ERROR = 'UPDATE_CART_ERROR';

export const REMOVE_FROM_CART_START = 'REMOVE_FROM_CART_START';
export const REMOVE_FROM_CART_END = 'REMOVE_FROM_CART_END';
export const REMOVE_FROM_CART_ERROR = 'REMOVE_FROM_CART_ERROR';

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const FILTER_CART = 'FILTER_CART';